W_LINE = 1.0
W_CHART = 80.0 * W_LINE
SPD_CHART = 1.5 * W_CHART # Units per second

H_SKINNY_NOTE = 1.5 * W_LINE
H_FAT_NOTE = 3.0 * H_SKINNY_NOTE

MISS_THRESHOLD = 50	# Milliseconds
HIT_THRESHOLD = MISS_THRESHOLD
